// We do not import at the top level to ensure lazy loading.
// import { GoogleGenAI } from "@google/genai"; 

export const generateAISticker = async (prompt: string): Promise<string> => {
  // Dynamically import the library only when the function is called.
  const { GoogleGenAI } = await import("@google/genai");

  // Check Local Storage first for User Provided Key
  const userKey = localStorage.getItem('collab_canvas_api_key');
  const apiKey = userKey || process.env.API_KEY;

  if (!apiKey) {
    throw new Error("API Key not found. Please add your key in Settings.");
  }

  const ai = new GoogleGenAI({ apiKey: apiKey });

  // Using gemini-2.5-flash-image for generation as per guidelines for general image tasks
  // when 'imagen' isn't explicitly requested by user features.
  // The prompt is engineered to produce a sticker-like graphic.
  const refinedPrompt = `Generate a high-quality, die-cut sticker graphic of: ${prompt}. 
  White border, flat vector art style, vibrant colors, isolated on white background.`;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            text: refinedPrompt,
          },
        ],
      },
      config: {
        // Nano banana models do not support responseMimeType or responseSchema
        // We rely on the model generating an image part
      }
    });

    // Iterate through parts to find the image
    const parts = response.candidates?.[0]?.content?.parts;
    if (parts) {
      for (const part of parts) {
        if (part.inlineData && part.inlineData.data) {
          const base64Data = part.inlineData.data;
          // Determine mime type if possible, usually png/jpeg from these models
          // The API returns IANA standard mime type in the object usually, but if not we assume PNG for stickers
          const mimeType = part.inlineData.mimeType || 'image/png';
          return `data:${mimeType};base64,${base64Data}`;
        }
      }
    }

    throw new Error("No image data generated by Gemini.");

  } catch (error) {
    console.error("Gemini Sticker Generation Error:", error);
    throw error;
  }
};